"""initial product and research schema

Revision ID: 18797ee84f1b
Revises: 
Create Date: 2026-07-17 23:18:18.329630
"""

from typing import Sequence, Union
from datetime import datetime, timezone

from alembic import op
import sqlalchemy as sa
import app.models.database


revision: str = '18797ee84f1b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('actor_type', sa.String(length=32), nullable=False),
    sa.Column('event', sa.String(length=64), nullable=False),
    sa.Column('email_hash', sa.String(length=64), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.String(length=128), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', app.models.database.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_event'), ['event'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_user_id'), ['user_id'], unique=False)

    op.create_table('dietitians',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('phone_verified', sa.Boolean(), nullable=False),
    sa.Column('specialization', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.models.database.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dietitians', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dietitians_email'), ['email'], unique=True)

    op.create_table('nutrition_sources',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('external_reference', sa.String(length=255), nullable=True),
    sa.Column('food_name', sa.String(length=255), nullable=False),
    sa.Column('calories_per_100g', sa.Float(), nullable=False),
    sa.Column('payload_checksum', sa.String(length=64), nullable=True),
    sa.Column('retrieved_at', app.models.database.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('survey_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('schema_json', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.models.database.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version')
    )
    survey_versions = sa.table(
        'survey_versions',
        sa.column('id', sa.String(length=36)),
        sa.column('version', sa.String(length=32)),
        sa.column('schema_json', sa.JSON()),
        sa.column('is_active', sa.Boolean()),
        sa.column('created_at', sa.DateTime(timezone=True)),
    )
    op.bulk_insert(survey_versions, [{
        'id': '00000000-0000-4000-8000-000000000001',
        'version': '1.0',
        'schema_json': {'seed': 'system-survey-definition'},
        'is_active': True,
        'created_at': datetime.now(timezone.utc),
    }])
    op.create_table('usability_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('participant_pseudonym', sa.String(length=36), nullable=False),
    sa.Column('session_date', app.models.database.UTCDateTime(), nullable=False),
    sa.Column('general_note', sa.String(length=1000), nullable=True),
    sa.Column('success_rate', sa.Float(), nullable=True),
    sa.Column('avg_task_duration', sa.Float(), nullable=True),
    sa.Column('created_at', app.models.database.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usability_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usability_sessions_participant_pseudonym'), ['participant_pseudonym'], unique=False)

    op.create_table('survey_submissions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('participant_pseudonym', sa.String(length=36), nullable=False),
    sa.Column('survey_version_id', sa.String(length=36), nullable=False),
    sa.Column('answers_json', sa.JSON(), nullable=False),
    sa.Column('completion_seconds', sa.Integer(), nullable=True),
    sa.Column('device_info', sa.String(length=255), nullable=True),
    sa.Column('submitted_at', app.models.database.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['survey_version_id'], ['survey_versions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('survey_submissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_survey_submissions_participant_pseudonym'), ['participant_pseudonym'], unique=False)
        batch_op.create_index(batch_op.f('ix_survey_submissions_submitted_at'), ['submitted_at'], unique=False)

    op.create_table('usability_tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('task_key', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('started_at', app.models.database.UTCDateTime(), nullable=True),
    sa.Column('ended_at', app.models.database.UTCDateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('is_success', sa.Boolean(), nullable=True),
    sa.Column('researcher_note', sa.String(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['usability_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usability_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usability_tasks_session_id'), ['session_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.models.database.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.models.database.UTCDateTime(), nullable=False),
    sa.Column('daily_calorie_target', sa.Float(), nullable=False),
    sa.Column('preferred_language', sa.String(length=10), nullable=False),
    sa.Column('tts_speed', sa.Float(), nullable=False),
    sa.Column('high_contrast', sa.Boolean(), nullable=False),
    sa.Column('dietitian_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['dietitian_id'], ['dietitians.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('dietitian_assignments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('dietitian_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'cancelled', name='assignment_status_enum'), nullable=False),
    sa.Column('created_at', app.models.database.UTCDateTime(), nullable=False),
    sa.Column('approved_at', app.models.database.UTCDateTime(), nullable=True),
    sa.Column('cancelled_at', app.models.database.UTCDateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dietitian_id'], ['dietitians.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dietitian_assignments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dietitian_assignments_dietitian_id'), ['dietitian_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dietitian_assignments_user_id'), ['user_id'], unique=False)

    op.create_table('dietitian_reports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('dietitian_id', sa.String(length=36), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('report_type', sa.Enum('daily', 'weekly', 'monthly', name='report_type_enum'), nullable=False),
    sa.Column('date_from', sa.Date(), nullable=False),
    sa.Column('date_to', sa.Date(), nullable=False),
    sa.Column('total_calories', sa.Float(), nullable=False),
    sa.Column('total_meals', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'sent', 'failed', name='report_status_enum'), nullable=False),
    sa.Column('sent_via_email', sa.Boolean(), nullable=False),
    sa.Column('sent_via_sms', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.models.database.UTCDateTime(), nullable=False),
    sa.Column('sent_at', app.models.database.UTCDateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dietitian_id'], ['dietitians.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'idempotency_key', name='uq_report_user_idempotency')
    )
    with op.batch_alter_table('dietitian_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dietitian_reports_user_id'), ['user_id'], unique=False)

    op.create_table('recognition_attempts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('succeeded', 'failed', name='recognition_status_enum'), nullable=False),
    sa.Column('food_name', sa.String(length=255), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('created_at', app.models.database.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recognition_attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recognition_attempts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_recognition_attempts_request_id'), ['request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recognition_attempts_user_id'), ['user_id'], unique=False)

    op.create_table('refresh_tokens',
    sa.Column('jti', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', app.models.database.UTCDateTime(), nullable=False),
    sa.Column('created_at', app.models.database.UTCDateTime(), nullable=False),
    sa.Column('revoked_at', app.models.database.UTCDateTime(), nullable=True),
    sa.Column('replaced_by_jti', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('jti'),
    sa.UniqueConstraint('token_hash')
    )
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refresh_tokens_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_refresh_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('consent_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('assignment_id', sa.String(length=36), nullable=True),
    sa.Column('consent_type', sa.String(length=64), nullable=False),
    sa.Column('policy_version', sa.String(length=32), nullable=False),
    sa.Column('granted', sa.Boolean(), nullable=False),
    sa.Column('granted_at', app.models.database.UTCDateTime(), nullable=False),
    sa.Column('revoked_at', app.models.database.UTCDateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['dietitian_assignments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('consent_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_consent_records_user_id'), ['user_id'], unique=False)

    op.create_table('food_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('recognition_attempt_id', sa.String(length=36), nullable=True),
    sa.Column('nutrition_source_id', sa.String(length=36), nullable=True),
    sa.Column('food_name', sa.String(length=255), nullable=False),
    sa.Column('food_name_tr', sa.String(length=255), nullable=False),
    sa.Column('calories_per_100g', sa.Float(), nullable=False),
    sa.Column('estimated_portion_g', sa.Float(), nullable=False),
    sa.Column('total_calories', sa.Float(), nullable=False),
    sa.Column('protein', sa.Float(), nullable=False),
    sa.Column('carbs', sa.Float(), nullable=False),
    sa.Column('fat', sa.Float(), nullable=False),
    sa.Column('fiber', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('meal_type', sa.Enum('kahvalti', 'ogle', 'aksam', 'atistirmalik', name='meal_type_enum'), nullable=False),
    sa.Column('recognition_source', sa.Enum('google_vision', 'tflite', 'manual', name='recognition_source_enum'), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('logged_at', app.models.database.UTCDateTime(), nullable=False),
    sa.Column('log_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['nutrition_source_id'], ['nutrition_sources.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['recognition_attempt_id'], ['recognition_attempts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('recognition_attempt_id')
    )
    with op.batch_alter_table('food_logs', schema=None) as batch_op:
        batch_op.create_index('idx_user_date', ['user_id', 'log_date'], unique=False)
        batch_op.create_index('idx_user_meal', ['user_id', 'meal_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_food_logs_log_date'), ['log_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_food_logs_logged_at'), ['logged_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_food_logs_user_id'), ['user_id'], unique=False)

    op.create_table('notification_deliveries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('report_id', sa.String(length=36), nullable=False),
    sa.Column('channel', sa.Enum('email', 'sms', name='notification_channel_enum'), nullable=False),
    sa.Column('status', sa.Enum('sent', 'failed', 'skipped', name='notification_status_enum'), nullable=False),
    sa.Column('provider_message_id', sa.String(length=255), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('attempted_at', app.models.database.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['dietitian_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_id', 'channel', name='uq_report_delivery_channel')
    )
    with op.batch_alter_table('notification_deliveries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_deliveries_report_id'), ['report_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification_deliveries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_deliveries_report_id'))

    op.drop_table('notification_deliveries')
    with op.batch_alter_table('food_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_food_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_food_logs_logged_at'))
        batch_op.drop_index(batch_op.f('ix_food_logs_log_date'))
        batch_op.drop_index('idx_user_meal')
        batch_op.drop_index('idx_user_date')

    op.drop_table('food_logs')
    with op.batch_alter_table('consent_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_consent_records_user_id'))

    op.drop_table('consent_records')
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_expires_at'))

    op.drop_table('refresh_tokens')
    with op.batch_alter_table('recognition_attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recognition_attempts_user_id'))
        batch_op.drop_index(batch_op.f('ix_recognition_attempts_request_id'))
        batch_op.drop_index(batch_op.f('ix_recognition_attempts_created_at'))

    op.drop_table('recognition_attempts')
    with op.batch_alter_table('dietitian_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dietitian_reports_user_id'))

    op.drop_table('dietitian_reports')
    with op.batch_alter_table('dietitian_assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dietitian_assignments_user_id'))
        batch_op.drop_index(batch_op.f('ix_dietitian_assignments_dietitian_id'))

    op.drop_table('dietitian_assignments')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('usability_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usability_tasks_session_id'))

    op.drop_table('usability_tasks')
    with op.batch_alter_table('survey_submissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_survey_submissions_submitted_at'))
        batch_op.drop_index(batch_op.f('ix_survey_submissions_participant_pseudonym'))

    op.drop_table('survey_submissions')
    with op.batch_alter_table('usability_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usability_sessions_participant_pseudonym'))

    op.drop_table('usability_sessions')
    op.drop_table('survey_versions')
    op.drop_table('nutrition_sources')
    with op.batch_alter_table('dietitians', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dietitians_email'))

    op.drop_table('dietitians')
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_events_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_events_event'))
        batch_op.drop_index(batch_op.f('ix_audit_events_created_at'))

    op.drop_table('audit_events')
    # ### end Alembic commands ###
